chat/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
    url(r'^$', 'chat.views.index', name='index'),
    url(r'^chat/(?P<chat_type>room|user)/(?P<oid>\d+)/$', 'chat.views.choice_chat_view', name="chat_view"),
)

simplechat/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'simplechat.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('registration.backends.simple.urls')),
    url(r'', include('chat.urls')),
    url(r'^login/', 'django.contrib.auth.views.login', name='login')
)

chat/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User


class Room(models.Model):
    name = models.CharField(max_length=25)

    def __unicode__(self):
        return u'{}'.format(self.name)

    class Meta:
        verbose_name = u'комната'
        verbose_name_plural = u'комнаты'

chat/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from .models import Room

# from django.core.urlresolvers import reverse
# room_url = lambda x: reverse('chat_view', args=['room', str(x.id)])


class RoomsForm(forms.Form):
    rooms = forms.ChoiceField(label=u'комнатах', choices=[('', '')] + [(o.pk, o.name) for o in Room.objects.all()])


class UsersForm(forms.Form):
    users = forms.ChoiceField(label=u'пользователем', choices=[('', '')] + [(o.pk, o.username) for o in User.objects.all()])

chat/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from chat.forms import UsersForm, RoomsForm
from .models import Room


@login_required
def index(request):
    return redirect('chat_view', chat_type='room', oid=1)

@login_required
def choice_chat_view(request, chat_type, oid):
    context = {
        'users': UsersForm(),
        'rooms': RoomsForm(),
        'id': oid,
        'chat_type': chat_type,
        'user': request.user
    }

    if chat_type == 'user':
        context['object'] = get_object_or_404(User, pk=oid)
    if chat_type == 'room':
        context['object'] = get_object_or_404(Room, pk=oid)

    return render(request, 'chat.html', context)

chat/templates/base.html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="/static/privatemessages.css">
<script type="text/javascript" src="http://yandex.st/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="/static/chat.js"></script>
<script type="text/javascript" src="/static/md5.js"></script>
{% block head %}{% endblock %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>{% block title %}Личные сообщения{% endblock title %}</title>
</head>
<body>
{% block content %}{% endblock content %}
</body>
</html>

chat/templates/chat.html
{% extends "base.html" %}

{% block title %}{{ partner.username }}{% endblock %}

{% block head %}
<script type="text/javascript">
    $(document).ready(function() {
        activate_my_chat("{{ chat_type }}", {{ id }});
        $('#id_users').change(function(){
            document.location.href = "/chat/user/"+$(this).val()+"/";
        })
        $('#id_rooms').change(function(){
            document.location.href = "/chat/room/"+$(this).val()+"/";
        })


    });
</script>
{% endblock %}

{% block content %}
<div class="chat">
    <div class="partner">
        <p class="messages">
            <span style="color: red;">{{ user.username }}</span>, Вы общаетесь с <span style="color: red;">{{ object }}</span>. Так же вы можете общаться с {{ users }} или в {{ rooms }}
        </p>
    </div>
    {% if object == user %}
        <h3>Согласен, иногда очень важно поговорить с самим собой %)</h3>

    {% else %}
    <div class="conversation" id="conversation">
    </div>

    <form class="message_form">
        <div class="compose">
            <textarea rows="1" cols="30" id="message_textarea"></textarea>
        </div>
        <div class="send">
            <button class="btn" type="button">Отправить от {{ user.username }}</button>
            <p>Вы также можете отправлять сообщения с помощью клавиш Ctrl + Enter.</p>
        </div>
    </form>
    {% endif %}
</div>

{% endblock content %}